// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/glydr-platform/GamePage.tsx": () => import("../components/mockups/glydr-platform/GamePage.tsx"),
  "./components/mockups/glydr-platform/Home.tsx": () => import("../components/mockups/glydr-platform/Home.tsx"),
  "./components/mockups/glydr-platform/ImportSuccess.tsx": () => import("../components/mockups/glydr-platform/ImportSuccess.tsx"),
  "./components/mockups/glydr-platform/ProfileDetail.tsx": () => import("../components/mockups/glydr-platform/ProfileDetail.tsx")
};
